### ISSUE TITLE
Cannot install on Python3

### ISSUE THREAD

**Issue by fonnesbeck** [ewheeler/pygrowup#8]
On the off-chance that someone is still maintaining this package, the installer is broken for Python 3. I get the following:

    /usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'entry_points'
      warnings.warn(msg)
    /usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'zip_safe'
      warnings.warn(msg)
    /usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'test_suite'
      warnings.warn(msg)
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: invalid command 'bdist_egg'
    /Users/fonnescj/GitHub/pygrowup/distribute-0.6.24-py3.4.egg
    Traceback (most recent call last):
      File "/Users/fonnescj/GitHub/pygrowup/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "setup.py", line 7, in <module>
        distribute_setup.use_setuptools()
      File "/Users/fonnescj/GitHub/pygrowup/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/Users/fonnescj/GitHub/pygrowup/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/Users/fonnescj/GitHub/pygrowup/distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    OSError: Could not build the egg.

Looks like some setup tools incompatibility.

**Comment by ewheeler** [comment]
Thanks, @fonnesbeck 
Haven't updated this for python3 compatibility. i'll add this to my list, but would welcome a PR in the meantime!

**Comment by ewheeler** [comment]
Hi @fonnesbeck -- just pushed an update that should support python3
Let me know if its working for you now

**Comment by fonnesbeck** [comment]
Sorry, just saw this now. Will test.

**Comment by jbaldivieso** [comment]
I'm still having trouble installing on Python 3.5:
```
(venv)[bash: ~/python/pygrowup] $ pip install pygrowup
Collecting pygrowup
  Using cached pygrowup-0.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.24.tar.gz
    Extracting in /var/folders/y_/_yh1ts790771vsj6r89b_zw00000gn/T/tmpo3hiw3ls
    Traceback (most recent call last):
      File "/private/var/folders/y_/_yh1ts790771vsj6r89b_zw00000gn/T/pip-build-veudroe7/pygrowup/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/y_/_yh1ts790771vsj6r89b_zw00000gn/T/pip-build-veudroe7/pygrowup/setup.py", line 4, in <module>
        distribute_setup.use_setuptools()
      File "/private/var/folders/y_/_yh1ts790771vsj6r89b_zw00000gn/T/pip-build-veudroe7/pygrowup/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/var/folders/y_/_yh1ts790771vsj6r89b_zw00000gn/T/pip-build-veudroe7/pygrowup/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/private/var/folders/y_/_yh1ts790771vsj6r89b_zw00000gn/T/pip-build-veudroe7/pygrowup/distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "/private/var/folders/y_/_yh1ts790771vsj6r89b_zw00000gn/T/pip-build-veudroe7/pygrowup/distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y_/_yh1ts790771vsj6r89b_zw00000gn/T/pip-build-veudroe7/pygrowup
```

**Comment by ewheeler** [comment]
@jbaldivieso hmm works for me

looks like you're trying to install to a directory within ```/private/var/``which is owned by root, so that might be an issue since unless you're logged in as root

**Comment by jbaldivieso** [comment]
I should have noted, @ewheeler -- this was all in the context of a brand new virtual environment running Python 3.5. (The fact that it's in /private/var/ is a red herring.) Is that how you're successfully installing it?

**Comment by jbaldivieso** [comment]
After further digging, it looks like it's a discrepancy in the method signature for tarfile.chown. The version of distribute_setup.py that ships with the package assumes needing to support Python 2.4, but with Python 2.5 and above, the standard library's tar support bundles its own extractall() method, making the auto-generated _extractall() function pygrownup uses unneeded. For instance, see this change: https://github.com/lxml/lxml/commit/e3cb59db4f616d1c8c591fe16b21c03c073dd346

I tried refactoring along those lines myself, but then ran into subsequent packaging issues. (Ideally, pygrownup can be repackaged as a wheel and get beyond supporting the now-obsolete `distribute`.)

**Comment by jbaldivieso** [comment]
(See pull request #9.)
